package com.progressterra.ipbandroidview.ui.login.country.enums

enum class Country(
    /**
     * Название русское
     */
    val titleRu: String,
    /**
     * Название английское
     */
    val titleEn: String,
    /**
     * Код
     */
    val phoneCode: String,
    /**
     * Код
     */
    val phoneStart: String? = null
) {
    AFGHANISTAN("Афганистан", "Afghanistan", "93"),
    ALBANIA("Албания", "Albania", "355"),
    ALGERIA("Алжир", "Algeria", "21"),
    AMERICAN_SAMOA("Американское Самоа", "American Samoa", "684"),
    ANDORRA("Андорра", "Andorra", "376"),
    ANGOLA("Ангола", "Angola", "244"),
    ANGUILLA("Ангуилла", "Anguilla", "1-264"),
    ANTIGUA_AND_BARBUDA("Антигуа и Барбуда", "Antigua and Barbuda", "1-268"),
    ARGENTINA("Аргентина", "Argentina", "54"),
    ARMENIA("Армения", "Armenia", "374"),
    ARUBA("Аруба", "Aruba", "297"),
    ASCENSION("Асеньон", "Ascension", "247"),
    AUSTRALIA("Австралия", "Australia", "61"),
    AUSTRALIAN_EXTERNAL_TERRITORIES(
        "Австралийские внешние территории",
        "Australian External Territories",
        "672"
    ),
    AUSTRIA("Австрия", "Austria", "43"),
    AZERBAIJAN("Азербайджан", "Azerbaijan", "994"),
    AZORES("Азорские о-ва", "Azores", "351"),
    BAHAMAS("Багамы", "Bahamas", "1-242"),
    BAHRAIN("Бахрейн", "Bahrain", "973"),
    BANGLADESH("Бангладеш", "Bangladesh", "880"),
    BARBADOS("Барбадос", "Barbados", "1-246"),
    BELARUS("Белоруссия", "Belarus", "375"),
    BELGIUM("Бельгия", "Belgium", "32"),
    BELIZE("Белиз", "Belize", "501"),
    BENIN("Бенин", "Benin", "229"),
    BERMUDA("Бермудские о-ва", "Bermuda", "1-441"),
    BHUTAN("Бутан", "Bhutan", "975"),
    BOLIVIA("Боливия", "Bolivia", "591"),
    BOSNIA_AND_HERZEGOVINA("Босния и Герцеговина", "Bosnia and Herzegovina", "387"),
    BOTSWANA("Ботсвана", "Botswana", "267"),
    BRAZIL("Бразилия", "Brazil", "55"),
    BRITISH_VIRGIN_ISLANDS("Британские Вирджинские о-ва", "British Virgin Islands", "1-284"),
    BRUNEI("Бруней", "Brunei", "673"),
    BULGARIA("Болгария", "Bulgaria", "359"),
    BURKINA_FASO("Буркина Фасо", "Burkina Faso", "226"),
    BURUNDI("Бурунди", "Burundi", "257"),
    CAMBODIA("Камбоджа", "Cambodia", "855"),
    CAMEROON("Камерун", "Cameroon", "237"),
    CAPE_VERDE("Капе Верде", "Cape Verde", "238"),
    CAYMAN_ISLANDS("Каймановы о-ва", "Cayman Islands", "1-345"),
    AFRICAN_REPUBLIC("ЦАР", "Central African Republic", "236"),
    CHAD("Чад", "Chad", "235"),
    CHILE("Чили", "Chile", "56"),
    CHINA("Китай", "China", "86"),
    CHRISTMAS_ISLAND("Рождественсткие о-ва", "Christmas Island", "672"),
    COCOS_ISLANDS("Кокосовые о-ва", "Cocos Islands", "672"),
    COLOMBIA("Колумбия", "Colombia", "57"),
    COMMONWEALTH_OF_THE_NORTHERN_M(
        "Содружество северных Мариански",
        "Commonwealth of the Northern M",
        "1-670"
    ),
    COMOROS_AND_MAYOTTE_ISLAND("Коморские о-ва", "Comoros and Mayotte Island", "269"),
    CONGO("Конго", "Congo", "242"),
    DEMOCRATIC_REPUBLIC("Дем. респ. Конго (бывш. Заир)", "Democratic Republic (ex. Zaire)", "243"),
    COOK_ISLANDS("О-ва Кука", "Cook Islands", "682"),
    COSTA_RICA("Коста Рика", "Costa Rica", "506"),
    CROATIA("Хорватия", "Croatia", "385"),
    CUBA("Куба", "Cuba", "53"),
    CYPRUS("Кипр", "Cyprus", "357"),
    CZECH_REPUBLIC("Чехия", "Czech Republic", "420"),
    DENMARK("Дания", "Denmark", "45"),
    DIEGO_GARCIA("Диего Гарсиа", "Diego Garcia", "246"),
    DJIBOUTI("Джибути", "Djibouti", "253"),
    DOMINICA("Доминика", "Dominica", "1-767"),
    DOMINICAN_REPUBLIC("Доминиканская республика", "Dominican Republic", "1-809"),
    EAST_TIMOR("Восточный Тимор", "East Timor", "62"),
    ECUADOR("Эквадор", "Ecuador", "593"),
    EGYPT("Египет", "Egypt", "20"),
    EL_SALVADOR("Сальвадор", "El Salvador", "503"),
    EQUATORIAL_GUINEA("Экваториальная Гвинея", "Equatorial Guinea", "240"),
    ERITREA("Эритрия", "Eritrea", "291"),
    ESTONIA("Эстония", "Estonia", "372"),
    ETHIOPIA("Эфиопия", "Ethiopia", "251"),
    FAEROE_ISLANDS("Фарерские о-ва", "Faeroe Islands", "298"),
    FALKLAND_ISLANDS("Фолклендские о-ва", "Falkland Islands", "500"),
    FIJI("Фиджи", "Fiji", "679"),
    FINLAND("Финляндия", "Finland", "358"),
    FRANCE("Франция", "France", "33"),
    FRENCH_ANTILLES("Французские Антиллы", "French Antilles", "590"),
    FRENCH_GUIANA("Французская Гвиана", "French Guiana", "594"),
    FRENCH_POLYNESIA("Французская полинезия", "French Polynesia", "689"),
    GABONESE_REPUBLIC("Габон", "Gabonese Republic", "241"),
    GAMBIA("Гамбия", "Gambia", "220"),
    GEORGIA("Грузия", "Georgia", "995"),
    GERMANY("Германия", "Germany", "49"),
    GHANA("Гана", "Ghana", "233"),
    GIBRALTAR("Гибралтар", "Gibraltar", "350"),
    GREECE("Греция", "Greece", "30"),
    GREENLAND("Гренландия", "Greenland", "299"),
    GRENADA("Гренада", "Grenada", "1-473"),
    GUAM("Гуам", "Guam", "671"),
    GUATEMALA("Гватемала", "Guatemala", "502"),
    GUINEA("Гвинея", "Guinea", "224"),
    GUINEA_BISSAU("Гвинея Биссау", "Guinea-Bissau", "245"),
    GUYANA("Гайана", "Guyana", "592"),
    HAITI("Гаити", "Haiti", "509"),
    HONDURAS("Гондурас", "Honduras", "504"),
    HONG_KONG("Гонконг", "Hong Kong", "852"),
    HUNGARY("Венгрия", "Hungary", "36"),
    ICELAND("Исландия", "Iceland", "354"),
    INDIA("Индия", "India", "91"),
    INDONESIA("Индонезия", "Indonesia", "62"),
    IRAN("Иран", "Iran", "98"),
    IRAQ("Ирак", "Iraq", "964"),
    IRISH_REPUBLIC("Ирландия", "Irish Republic", "353"),
    ISRAEL("Израиль", "Israel", "972"),
    ITALY("Италия", "Italy", "39"),
    IVORY_COAST("Берег слоновой кости", "Ivory Coast", "225"),
    JAMAICA("Ямайка", "Jamaica", "1-876"),
    JAPAN("Япония", "Japan", "81"),
    JORDAN("Иордания", "Jordan", "962"),
    KAZAKHSTAN("Казахстан", "Kazakhstan", "7"),
    KENYA("Кения", "Kenya", "254"),
    KIRIBATI_REPUBLIC("Кирибати", "Kiribati Republic", "686"),
    KOREA_DEM("Северная Корея", "Korea, Dem. Peoples Republic", "850"),
    KOREA("Южная Корея", "Korea Republic", "82"),
    KUWAIT("Кувейт", "Kuwait", "965"),
    KYRGYZSTAN("Киргизстан", "Kyrgyzstan", "996"),
    LAOS("Лаос", "Laos", "856"),
    LATVIA("Латвия", "Latvia", "371"),
    LEBANON("Ливан", "Lebanon", "961"),
    LESOTHO("Лессото", "Lesotho", "266"),
    LIBERIA("Либерия", "Liberia", "231"),
    LIBYA("Ливия", "Libya", "21"),
    LIECHTENSTEIN("Лихтенштейн", "Liechtenstein", "41"),
    LITHUANIA("Литва", "Lithuania", "370"),
    LUXEMBOURG("Люксембург", "Luxembourg", "352"),
    MACAU("Макао", "Macau", "853"),
    MACEDONIA("Македония", "Macedonia", "389"),
    MADAGASCAR("Мадагаскар", "Madagascar", "261"),
    MALAWI("Малави", "Malawi", "265"),
    MALAYSIA("Малайзия", "Malaysia", "60"),
    MALDIVES("Мальдивские о-ва", "Maldives", "960"),
    MALI("Мали", "Mali", "223"),
    MALTA("Мальта", "Malta", "356"),
    MARSHALL_ISLANDS("Маршалловы о-ва", "Marshall Islands", "692"),
    MARTINIQUE("Мартиника", "Martinique", "596"),
    MAURITANIA("Мавритания", "Mauritania", "222"),
    MAURITIUS("Маврикий", "Mauritius", "230"),
    MEXICO("Мексика", "Mexico", "52"),
    MICRONESIA("Микронезия", "Micronesia", "691"),
    MONACO("Монако", "Monaco", "377"),
    MONGOLIA("Монголия", "Mongolia", "976"),
    MONTSERRAT("Монсеррат", "Montserrat", "1-664"),
    MOLDOVA("Молдавия", "Moldova", "373"),
    MOROCCO("Марокко", "Morocco", "212"),
    MOZAMBIQUE("Мозамбик", "Mozambique", "258"),
    MYANMAR("Мьянма", "Myanmar", "95"),
    NAMIBIA("Намибия", "Namibia", "264"),
    NAURU("Науру", "Nauru", "674"),
    NEPAL("Непал", "Nepal", "977"),
    NETHERLANDS("Нидерланды", "Netherlands", "31"),
    NETHERLANDS_ANTILLES("Нидерландские Антиллы", "Netherlands Antilles", "599"),
    NEW_CALEDONI("Новая Каледония", "New Caledonia", "687"),
    NEW_ZEALAND("Новая Зеландия", "New Zealand", "64"),
    NICARAGUA("Никарагуа", "Nicaragua", "505"),
    NIGER("Нигер", "Niger", "227"),
    NIGERIA("Нигерия", "Nigeria", "234"),
    NIUE_ISLANDS("НИУЭ", "Niue Islands", "683"),
    NORFOLK_ISLAND("Норфолкские о-ва", "Norfolk Island", "672"),
    NORTHERN_MARIANA_ISLANDS("Северо-Марианские о-ва", "Northern Mariana Islands", "670"),
    NORWAY("Норвегия", "Norway", "47"),
    OMAN("Оман", "Oman", "968"),
    PAKISTAN("Пакистан", "Pakistan", "92"),
    PALAU("Палау", "Palau", "680"),
    PANAMA("Панама", "Panama", "507"),
    PAPUA_NEW_GUINEA("Папуа Новая Гвинея", "Papua New Guinea", "675"),
    PARAGUAY("Парагвай", "Paraguay", "595"),
    PERU("Перу", "Peru", "51"),
    PHILIPPINES("Филипины", "Philippines", "63"),
    POLAND("Польша", "Poland", "48"),
    PORTUGAL("Португалия", "Portugal", "351"),
    PUERTO_RICO("Пуэрто Рико", "Puerto Rico", "1-787"),
    QATAR("Катар", "Qatar", "974"),
    REPUBLIC_OF_SAN_MARINO("Сан Марино", "Republic of San Marino", "378"),
    REUNION_ISLANDS("Реюнион", "Reunion Islands", "262"),
    ROMANIA("Румыния", "Romania", "40"),
    RUSSIA("Россия", "Russia", "7", "9"),
    RWANDESE_REPUBLIC("Руанда", "Rwandese Republic", "250"),
    SAINT_HELENA_AND_ASCENSION_ISL("О-ва Святой Елены", "Saint Helena and Ascension Isl", "247"),
    SAINT_PIERRE_ET_MIQUELON("Сент Пьер", "Saint Pierre et Miquelon", "508"),
    SAN_MARINO("Сан Марино", "San Marino", "39"),
    SAO_TOME_E_PRINCIPE("Сент Том и Принцип", "Sao Tome e Principe", "239"),
    SAUDI_ARABIA("Саудовская Аравия", "Saudi Arabia", "966"),
    SENEGAL("Сенегал", "Senegal", "221"),
    SEYCHELLES("Сейшельские о-ва", "Seychelles", "248"),
    SIERRA_LEONE("Сьерра Леоне", "Sierra Leone", "232"),
    SINGAPORE("Сингапур", "Singapore", "65"),
    SLOVAK_REPUBLIC("Словакия", "Slovak Republic", "421"),
    SLOVENIA("Словения", "Slovenia", "386"),
    SOLOMON_ISLANDS("Соломоновы о-ва", "Solomon Islands", "677"),
    SOMALIA("Сомали", "Somalia", "252"),
    SOUTH_AFRICA("ЮАР", "South Africa", "27"),
    SPAIN("Испания", "Spain", "34"),
    SRI_LANKA("Шри Ланка", "Sri Lanka", "94"),
    ST_KITTS_AND_NEVIS("Сент-Китс и Невис", "St. Kitts and Nevis", "1-869"),
    ST_LUCIA("Санта Лючия", "St. Lucia", "1-758"),
    ST_VINCENT_AND_THE_GRENADINES(
        "Сент Винцент и Гренадины",
        "St. Vincent and the Grenadines",
        "1-784"
    ),
    SUDAN("Судан", "Sudan", "249"),
    SURINAME("Суринам", "Suriname", "597"),
    SVALBARD_AND_JAN_MAYEN_ISLANDS("Свалбард", "Svalbard and Jan Mayen Islands", "47"),
    SWAZILAND("Свазиленд", "Swaziland", "268"),
    SWEDEN("Швеция", "Sweden", "46"),
    SWITZERLAND("Швейцария", "Switzerland", "41"),
    SYRIA("Сирия", "Syria", "963"),
    TAIWAN("Тайвань", "Taiwan", "886"),
    TAJIKISTAN("Таджикистан", "Tajikistan", "992"),
    TANZANIA("Танзания", "Tanzania", "255"),
    THAILAND("Тайланд", "Thailand", "66"),
    TOGOLESE_REPUBLIC("Тоголезе", "Togolese Republic", "228"),
    TOKELAU("Токелау", "Tokelau", "690"),
    TONGA("Тонго", "Tonga", "676"),
    TRINIDAD_AND_TOBAGO("Тринидад и Тобаго", "Trinidad and Tobago", "1-868"),
    TUNISIA("Тунис", "Tunisia", "21"),
    TURKEY("Турция", "Turkey", "90"),
    TURKMENISTAN("Туркменистан", "Turkmenistan", "993"),
    TURKS("Текс и Каикос Айландс", "Turks & Caicos Islands", "1-649"),
    TUVALU("Тувалу", "Tuvalu", "688"),
    UGANDA("Уганда", "Uganda", "256"),
    UKRAINE("Украина", "Ukraine", "380"),
    UNITED_ARAB_EMIRATES("ОАЭ", "United Arab Emirates", "971"),
    UNITED_KINGDOM("Великобритания", "United Kingdom", "44"),
    URUGUAY("Уругвай", "Uruguay", "598"),
    US_VIRGIN_ISLANDS("Вирджинские о-ва", "US Virgin Islands", "1-340"),
    USA("США", "USА", "1"),
    UZBEKISTAN("Узбекистан", "Uzbekistan", "998"),
    VANUATU("Вануату", "Vanuatu", "678"),
    VATICAN_CITY_STATE("Ватикан", "Vatican City State", "39"),
    VENEZUELA("Венесуэла", "Venezuela", "58"),
    VIETNAM("Вьетнам", "Vietnam", "84"),
    WALLIS_AND_FUTUNA("Эллис и Футуна острова", "Wallis and Futuna", "681"),
    WESTERN_SAHARA("Западная Сахара", "Western Sahara", "21"),
    WESTERN_SAMOA("Западное Самоа", "Western Samoa", "685"),
    YEMEN_NORTH("Северный Йемен", "Yemen, North", "967"),
    YEMEN_SOUTH("Южный Йемен", "Yemen, South", "969"),
    YUGOSLAVIA("Югославия", "Yugoslavia", "381"),
    ZAIRE("Заир", "Zaire", "243"),
    ZAMBIA("Замбия", "Zambia", "260"),
    ZANZIBAR("Занзибар", "Zanzibar", "259"),
    ZIMBABWE("Зимбабве", "Zimbabwe", "263");
}