package com.progressterra.ipbandroidview.composable.pages.proshkamain

import com.progressterra.ipbandroidview.features.UseProshkaBonuses
import com.progressterra.ipbandroidview.shared.ui.UseStateBox
import com.progressterra.ipbandroidview.widgets.UseProshkaGalleries
import com.progressterra.ipbandroidview.widgets.UseProshkaOffers

interface ProshkaMainScreenInteractor : UseProshkaGalleries, UseProshkaOffers, UseProshkaBonuses, UseStateBox