package com.progressterra.ipbandroidview.ui.order

import com.progressterra.ipbandroidview.composable.component.ReceiptComponentEvent
import com.progressterra.ipbandroidview.core.ComponentEventHandler

interface ReceiptComponentEventHandler : ComponentEventHandler<ReceiptComponentEvent>