package com.progressterra.ipbandroidview.ui.city

import com.progressterra.ipbandroidview.composable.component.MapComponentEvent
import com.progressterra.ipbandroidview.core.ComponentEventHandler

interface MapComponentEventHandler : ComponentEventHandler<MapComponentEvent>