package com.progressterra.ipbandroidview.widgets.edituser

import com.progressterra.ipbandroidview.features.makephoto.UseMakePhoto
import com.progressterra.ipbandroidview.features.citizenshipsuggestions.UseCitizenshipSuggestions
import com.progressterra.ipbandroidview.shared.ui.textfield.UseTextField

interface UseEditUser : UseTextField, UseMakePhoto, UseCitizenshipSuggestions